'use client'
import '../styles/style.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Nav from './components/Navbar/Nav'
const inter = Inter({ subsets: ['latin'] })
import Side from './components/Sidebar/Side'
import { Provider } from 'react-redux'
import { store } from '@/redux/store'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>
          <div className='container'>
            <Nav />
            <div className="content">
              <Side />
              {children}
            </div>
          </div>
        </Provider>
      </body>
    </html>
  )
}
